# config/app.yml for rails-settings-cached
defaults: &defaults
  titulo_coordinador: "Lcda."
  nombres_coordinador: "Grecia Marcano"
  cedula_coordinador: "V-16.932.173"
  jornada_de_trabajo_inicio: "8:00 a.m"
  jornada_de_trabajo_fin: "3:30 p.m"
  email_admin: "admin@admin.com"

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
